# Generated by Django 2.2.20 on 2021-05-17 14:29

from django.db import migrations
import phonenumbers


def normalize_owners_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        try:
            parsed_phonenumber = phonenumbers.parse(flat.owners_phonenumber, 'RU')

            if not phonenumbers.is_valid_number(parsed_phonenumber):
                flat.owner_pure_phone = ""
            else:
                flat.owner_pure_phone = parsed_phonenumber

        except phonenumbers.phonenumberutil.NumberParseException:
            flat.owner_pure_phone = ""
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_owners_phone_numbers),
    ]
