# Generated by Django 2.2.20 on 2021-05-17 15:13

from django.db import migrations


def copy_owners_from_flats(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20210517_2209'),
    ]

    operations = [
        migrations.RunPython(copy_owners_from_flats),
    ]
