# Generated by Django 2.2.20 on 2021-05-17 16:24

from django.db import migrations


def copy_flats_relations_to_owner(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for owner in Owner.objects.all():
        owner.flats.set(
            Flat.objects.filter(
                owner=owner.owner,
                owners_phonenumber=owner.owners_phonenumber,
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20210517_2324'),
    ]

    operations = [
        migrations.RunPython(copy_flats_relations_to_owner),
    ]
